//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WpfAppForTask5.StudentListServise {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MyWebServiceSoap", Namespace="http://www.mycompany.com/")]
    public partial class MyWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentsGraterThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentsLowerThanOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentsInRangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MyWebService() {
            this.Url = global::WpfAppForTask5.Properties.Settings.Default.WpfAppForTask5_StudentListServise_MyWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetStudentsGraterThanCompletedEventHandler GetStudentsGraterThanCompleted;
        
        /// <remarks/>
        public event GetStudentsLowerThanCompletedEventHandler GetStudentsLowerThanCompleted;
        
        /// <remarks/>
        public event GetStudentsInRangeCompletedEventHandler GetStudentsInRangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mycompany.com/HelloWorld", RequestNamespace="http://www.mycompany.com/", ResponseNamespace="http://www.mycompany.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld(string text) {
            object[] results = this.Invoke("HelloWorld", new object[] {
                        text});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string text) {
            this.HelloWorldAsync(text, null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(string text, object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[] {
                        text}, this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mycompany.com/GetStudentsGraterThan", RequestNamespace="http://www.mycompany.com/", ResponseNamespace="http://www.mycompany.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Student[] GetStudentsGraterThan(float mark) {
            object[] results = this.Invoke("GetStudentsGraterThan", new object[] {
                        mark});
            return ((Student[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentsGraterThanAsync(float mark) {
            this.GetStudentsGraterThanAsync(mark, null);
        }
        
        /// <remarks/>
        public void GetStudentsGraterThanAsync(float mark, object userState) {
            if ((this.GetStudentsGraterThanOperationCompleted == null)) {
                this.GetStudentsGraterThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentsGraterThanOperationCompleted);
            }
            this.InvokeAsync("GetStudentsGraterThan", new object[] {
                        mark}, this.GetStudentsGraterThanOperationCompleted, userState);
        }
        
        private void OnGetStudentsGraterThanOperationCompleted(object arg) {
            if ((this.GetStudentsGraterThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentsGraterThanCompleted(this, new GetStudentsGraterThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mycompany.com/GetStudentsLowerThan", RequestNamespace="http://www.mycompany.com/", ResponseNamespace="http://www.mycompany.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Student[] GetStudentsLowerThan(float mark) {
            object[] results = this.Invoke("GetStudentsLowerThan", new object[] {
                        mark});
            return ((Student[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentsLowerThanAsync(float mark) {
            this.GetStudentsLowerThanAsync(mark, null);
        }
        
        /// <remarks/>
        public void GetStudentsLowerThanAsync(float mark, object userState) {
            if ((this.GetStudentsLowerThanOperationCompleted == null)) {
                this.GetStudentsLowerThanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentsLowerThanOperationCompleted);
            }
            this.InvokeAsync("GetStudentsLowerThan", new object[] {
                        mark}, this.GetStudentsLowerThanOperationCompleted, userState);
        }
        
        private void OnGetStudentsLowerThanOperationCompleted(object arg) {
            if ((this.GetStudentsLowerThanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentsLowerThanCompleted(this, new GetStudentsLowerThanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.mycompany.com/GetStudentsInRange", RequestNamespace="http://www.mycompany.com/", ResponseNamespace="http://www.mycompany.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Student[] GetStudentsInRange(float minMark, float maxMark) {
            object[] results = this.Invoke("GetStudentsInRange", new object[] {
                        minMark,
                        maxMark});
            return ((Student[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentsInRangeAsync(float minMark, float maxMark) {
            this.GetStudentsInRangeAsync(minMark, maxMark, null);
        }
        
        /// <remarks/>
        public void GetStudentsInRangeAsync(float minMark, float maxMark, object userState) {
            if ((this.GetStudentsInRangeOperationCompleted == null)) {
                this.GetStudentsInRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentsInRangeOperationCompleted);
            }
            this.InvokeAsync("GetStudentsInRange", new object[] {
                        minMark,
                        maxMark}, this.GetStudentsInRangeOperationCompleted, userState);
        }
        
        private void OnGetStudentsInRangeOperationCompleted(object arg) {
            if ((this.GetStudentsInRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentsInRangeCompleted(this, new GetStudentsInRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mycompany.com/")]
    public partial class Student {
        
        private string nameField;
        
        private float avgMarkField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public float AvgMark {
            get {
                return this.avgMarkField;
            }
            set {
                this.avgMarkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetStudentsGraterThanCompletedEventHandler(object sender, GetStudentsGraterThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentsGraterThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentsGraterThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Student[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Student[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetStudentsLowerThanCompletedEventHandler(object sender, GetStudentsLowerThanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentsLowerThanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentsLowerThanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Student[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Student[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetStudentsInRangeCompletedEventHandler(object sender, GetStudentsInRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentsInRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentsInRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Student[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Student[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591